### ISSUE TITLE
Use with http and Homebridge

### ISSUE THREAD

**Issue by Kepete** [nidayand/motor-on-roller-blind-ws#12]
First thank you for your development. 

I would like to use this with the a Homebridge plugin that can control blinds over http. Plugin here: https://github.com/Nicnl/homebridge-minimal-http-blinds 

I need a `get_current_position_url` that will return the current blinds position in plaintext, from 0 to 100.
I need a `set_target_position_url` that will trigger the blinds movement. 
I need `get_current_state_url` that will return the state of the blinds in plaintext. 

Is this possible to do with your project? Would love to use yours because of easy setup and nice web-interface.

**Comment by nidayand** [comment]
Hi, I'm not a Homebridge user and will not build that into the code but you are of course free to fork my project and modify it as much as you like to. It is not supporting HTTP requests to control it today but you can build a bridging app as all the values are available.
