### ISSUE TITLE
Motor not rotating

### ISSUE THREAD

**Issue by andrewjdavison** [nidayand/motor-on-roller-blind-ws#17]
When I upload the sketch the web portals present themselves correctly, but I notice that D3 & D4 on the ULN2003 controller stay lit. On "starting" the motor, all four lights come on and the motor vibrates but does not rotate. It seems like the stepper algorithm isn't working correctly. Is this possibly another artefact of an updated library that hasn't been addressed as yet?

Can you tell us which versions of the libraries you have compiled with?

**Comment by nidayand** [comment]
It more sounds to me that your wiring is not correct. The stepper library hasn't changed for 2 years...

**Comment by andrewjdavison** [comment]
Sorry - I meant to close this. The board model was wrong so the DIO mapping was incorrect.

**Comment by nidayand** [comment]
👍
