### ISSUE TITLE
Possible to add second stepper motor with inverse rotation direction?

### ISSUE THREAD

**Issue by kristapsdravnieks** [nidayand/motor-on-roller-blind-ws#21]
Hi!
I printed all parts and put together. if blind is fully open, motor don't have enough torque to pull it back up.
is it possible to program second stepper driver with inverse direction on pins D5,D6,D7,D8? if pins not used, it would not affect operation on smaller blinds.

**Comment by oyvindkinsey** [comment]
No need for this, simply flip the wiring to the motor and it will go the other way.
