### ISSUE TITLE
Webpage not showing up

### ISSUE THREAD

**Issue by owenselles** [nidayand/motor-on-roller-blind-ws#25]
I flashed the esp successfully and I am able to access the page and set up the wifi and mqtt settings but after I did that and I go to my esp IP address Firefox just says unable to connect. Is there something i am doing wrong?

**Comment by owenselles** [comment]
Also when flashing at 9600 rate it stops at 47% and days done uploading

**Comment by philips1981** [comment]
Same problem here.

**Comment by martikainen87** [comment]
I started this project yesterday and had the same issues, I think it's because of the different libraries and version which is incompatible. I found a combination that works,

Download this precompiled bin and flash it with esptool.py, and erase the flash before doing it 

https://1drv.ms/u/s!AgpjVMpYqcPxitpNmqlQ6YSR00wzVg

```
esptool.py --port COM7 erase_region 0x0F4000 0x008000
esptool.py --port COM7 erase_flash
esptool.py --port COM7 write_flash -fs 1MB -fm dout 0x0 motor_on_a_roller_blind-ws.ino.nodemcu.bin.bin

```

**Comment by wildcatquebec** [comment]
Hello (Sorry for my english) i have a similar problem; i "fix it"  with your .bin
I haved always a Exception 28 with a memory dump.

Now with your code i have this in the Serial Monitor:

*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 3
*WM: IP Address:
*WM: 192.168.0.115
Failed to mount file system
*WM: freeing allocated params!
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
........

I don't want to use MQTT; I see its optional but in this case is look loop with this error.

**Comment by owenselles** [comment]
Thanks, it worked for me!

**Comment by Impertus** [comment]
Hi. I Aldo got the webpage to work with the bin file.

But when i Will rotate the motor is only humming.

Is it wrong pins or? Using D1 to D4
