### ISSUE TITLE
Possible to add button feature to control blinds manually?

### ISSUE THREAD

**Issue by bonze4** [nidayand/motor-on-roller-blind-ws#27]
It would be nice to be able to connect two buttons to the board for manual controlling of the blind.
I have the following concept in mind:

1. Button: 
single press: open
long press: upwards movement during hold

2. Button:
single press: close
long press: downwards movement during hold

**Comment by nidayand** [comment]
Hi, I don't plan to add buttons but feel free to fork the repository. I want to keep it as simple as possible as any additions will impact performance. Personally, I'm using wireless buttons to control the device over MQTT.
