### ISSUE TITLE
dont have WIFI hotspot named BlindsConnectAP

### ISSUE THREAD

**Issue by lukaszwitkowski** [nidayand/motor-on-roller-blind-ws#6]
help i dont have WIFI hotspot named BlindsConnectAP. my board connect to my wifi automatic after flashing and i dont have mqtt setings only calibration page and controll page. can i open mqtt setings page like in your photos in description? sory for my english

**Comment by nidayand** [comment]
You need to clear your flash memory. Your settings are most likely stored from a previous flash.. Either uncomment
//clean FS, for testing
  //helper.resetsettings(wifiManager);
or use a tool such as esptool.py to clear the flash prior to reflash with my code
