### ISSUE TITLE
Home bridge

### ISSUE THREAD

**Issue by lukaszwitkowski** [nidayand/motor-on-roller-blind-ws#8]
Hello i Want to use mqtt in my homebridge.
Can You tell me what pulling gona be best and hav to configure.

**Comment by nidayand** [comment]
HI, I don't understand the question. Please elaborate

**Comment by lukaszwitkowski** [comment]
I want to use sonething to comunicate witch mqtt
But that dont work
https://github.com/bonze4/homebridge-mqtt-blinds

**Comment by lukaszwitkowski** [comment]
My blind
Send message to mqtt
/raw/esp8266/8959633/out { „set”:51, „position”:51 }
And my tablet send message to mqtt
/raw/esp8266/8959633/out/SET/targetPosition 30
When i change to „in”
/raw/esp8266/8959633/in/SET/targetPosition 30
Nothing work

**Comment by nidayand** [comment]
The problem with homebridge-mqtt-blinds is that it is using the topic to control the blind and not the payload - it is a matter of design. So you either have to create new new fork of homebridge-mqtt-blinds or motor-on-roller-blind-we to modify the messages being sent. This repo only has one topic that it listens to and that is the "/raw/esp8266/8959633/in" topic.

**Comment by lukaszwitkowski** [comment]
For what you add mqtt? Do you use mqtt to something? Do you have kind of pulling?

**Comment by nidayand** [comment]
I personally only use MQTT to control my blinds. I have a wireless Xiaomi button and I use Google Home voice control to steer my blinds

**Comment by nidayand** [comment]
Pulling is available - if you mean requesting a status.. Just send '(update)' and it will post the current position

**Comment by nidayand** [comment]
I got it. In summary you need to modify the code in one end..
